name: grpc_cloud_firestore
description: "gRPC Cloud Firestore library implementation for Flutter allowing to run on Flutter Desktop"
version: 1.0.0
homepage: https://github.com/tomasweigenast/grpc_cloud_firestore

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.1
  cloud_firestore: ^4.14.0
  cloud_firestore_platform_interface: ^6.1.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
